CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS PEOPLE(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    BIRTH_DATE DATE NOT NULL,
    FIRST_NAME VARCHAR(120) NOT NULL,
    LAST_NAME VARCHAR(70) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PEOPLE_ID PRIMARY KEY(ID)
);

CREATE INDEX PEOPLE_FIRST_NAME_IDX ON public.PEOPLE USING btree (FIRST_NAME);