CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS COMPANIES(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    FANTASY_NAME VARCHAR(120) NOT NULL,
    SOCIAL_REASON VARCHAR(70) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COMPANIES_ID PRIMARY KEY(ID)
);

CREATE INDEX COMPANIES_FANTASY_NAME_IDX ON public.COMPANIES USING btree (FANTASY_NAME);
CREATE INDEX COMPANIES_SOCIAL_REASON_IDX ON public.COMPANIES USING btree (SOCIAL_REASON);